# Generated by Django 3.1.7 on 2021-04-02 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.CharField(default='3b31076b-2317-3868-f6254ef7d099', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('owned_by', models.CharField(max_length=100, unique=True, verbose_name='Owned By')),
                ('is_disabled', models.BooleanField(default=True)),
                ('status_last_updated', models.DateTimeField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.CharField(default='11d780ef-52e0-d2f3-4aacdf26b714', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('type', models.CharField(choices=[('withdrawals', 'withdrawals'), ('deposits', 'deposits')], max_length=100000)),
                ('transaction_by', models.CharField(max_length=100000, verbose_name='Transaction By')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('pending', 'pending')], max_length=100000)),
                ('reference_id', models.CharField(max_length=100000, unique=True, verbose_name='Referance Id')),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletapi.wallet')),
            ],
        ),
    ]
